# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 11:33
from __future__ import unicode_literals

import barbados.barbadosdb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(blank=True, choices=[('', '--------'), ('M', 'Motorboat'), ('S', 'Sailboat')], db_column='type', default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='boat',
            name='draught',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='inspection_class',
            field=models.IntegerField(blank=True, choices=[(None, '--------'), (1, 'Offshore'), (2, 'Coastal'), (3, 'Archipelago')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='insurance_company',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='boat',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='boat',
            name='material',
            field=models.CharField(blank=True, choices=[('', '--------'), ('F', 'Fibreglass'), ('W', 'Wood'), ('M', 'Metal'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='boat',
            name='model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='boat',
            name='registration_number',
            field=barbados.barbadosdb.models.RegistrationNumberField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='boat',
            name='weight',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='FI', max_length=2, null=True),
        ),
    ]
