# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:21
from __future__ import unicode_literals

from django.db import migrations


def create_groups(apps, schema_editor):
    """Go with this instead of fixtures
    """

    Group = apps.get_model('auth', 'Group')
    for group_name in ('Membership secretary', 'Harbourmaster', 'Committee member'):
        Group.objects.create(name=group_name)


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0003_draught_weight'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
