# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0004_permission_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berth',
            options={'permissions': (('assign_berth_boat', 'Can assign a berth to a boat'),)},
        ),
        migrations.AlterModelOptions(
            name='jetty',
            options={'verbose_name_plural': 'Jetties'},
        ),
        migrations.AlterField(
            model_name='boat',
            name='beam',
            field=models.IntegerField(blank=True, default=None, help_text='Centimetres', null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='draught',
            field=models.IntegerField(blank=True, default=None, help_text='Centimetres', null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='height',
            field=models.IntegerField(blank=True, default=None, help_text='Centimetres', null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='length',
            field=models.IntegerField(blank=True, default=None, help_text='Centimetres', null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='weight',
            field=models.IntegerField(blank=True, default=None, help_text='Kilograms', null=True),
        ),
    ]
