# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:21
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions

from django.db import migrations, models


def make_permissions(apps, schema_editor):
    """Borrowed from
    https://code.djangoproject.com/ticket/23422#comment:6
    """

    assert not getattr(apps, 'models_module', None)
    apps.models_module = True

    create_permissions(apps, verbosity=0)

    apps.models_module = None


def assign_permissions(apps, schema_editor):
    """Go with this instead of fixtures
    """

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group_defs = {'Membership secretary': ('add_user', 'change_user', 'delete_user',
                                            'add_boat', 'change_boat', 'delete_boat'),
                'Harbourmaster': ('assign_berth_boat', 'deny_berth_boat')}

    permissions = {}
    relevant_objs = models.Q(codename__contains='user') | models.Q(codename__contains='boat')
    for permission in Permission.objects.filter(relevant_objs):
        permissions[permission.codename] = permission

    for group_name, perms in group_defs.items():
        group = Group.objects.get(name=group_name)
        perms = (permissions[perm] for perm in perms)
        group.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
        ('barbadosdb', '0005_berth_perms'),
    ]

    operations = [
        migrations.RunPython(make_permissions),
        migrations.RunPython(assign_permissions),
    ]

