# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 12:43
from __future__ import unicode_literals

import barbados.barbadosdb.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0006_assign_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbadosdb.Club')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=barbados.barbadosdb.fields.PhoneNumberField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ManyToManyField(through='barbadosdb.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
