# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0007_club_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='user',
            new_name='users',
        ),
    ]
