# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 12:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0008_club_users2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='jetty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berths', to='barbadosdb.Jetty'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='hull_inspection_year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2015)]),
        ),
        migrations.AlterField(
            model_name='boat',
            name='inspection_year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2015)]),
        ),
        migrations.AlterField(
            model_name='boat',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator(message='Registration number must be blank or of form A12345', regex='[A-Z][0-9]{1,5}')]),
        ),
        migrations.AlterField(
            model_name='boat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='harbour',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harbours', to='barbadosdb.Club'),
        ),
        migrations.AlterField(
            model_name='jetty',
            name='harbour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetties', to='barbadosdb.Harbour'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=24, validators=[django.core.validators.RegexValidator(message='Use international format with phone numbers', regex='^\\+[0-9/ .()]+$')]),
        ),
    ]
