# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbadosdb', '0009_auto_20151215_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berth',
            options={'permissions': (('view_berth', 'Can view a berth'), ('assign_berth_boat', 'Can assign a berth to a boat'), ('deny_berth_boat', 'Can deny a berth from a boat'))},
        ),
        migrations.AlterModelOptions(
            name='boat',
            options={'permissions': (('view_boat', 'Can view a boat'), ('view_own_boat', 'Can view own boat'))},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': (('view_club', 'Can view a club'),)},
        ),
        migrations.AlterModelOptions(
            name='harbour',
            options={'permissions': (('view_harbour', 'Can view a harbour'),)},
        ),
        migrations.AlterModelOptions(
            name='jetty',
            options={'permissions': (('view_jetty', 'Can view a jetty'),), 'verbose_name_plural': 'Jetties'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view a user'), ('view_own_user', 'Can view own user'), ('change_own_user', 'Can change own user'))},
        ),
    ]
